### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by xiaogouaiyaotou** [epfl-labos/x-stream#11]
**Hello, there's a input data file type trouble when I try to use your code,this is the link of the file I used http://snap.stanford.edu/data/wiki-Vote.html . This input file is a edge list file ,I want to convert it to binary edge list used the tool you provided. Unfortunately, some details of your convert program input file has a little bit different between me. So I have to make a little change in the convert file below**
### for line in infile:
    if line[0] == '#':
        pass
    else:
        vector = line.strip().split("\t")                               
        vector = list(map(int,vector))
        vector.append(random.random()) # Edge weight
        if vector[0] > vertices:                                          //I delete minus 1 operate here
            vertices = vector[0]
        if vector[1] > vertices:
            vertices = vector[1]
        edges = edges + 1
        outfile.write(s.pack(*vector))
        if add_rev_edges:
            edges = edges + 1
            tmp = vector[0]
            vector[0] = vector[1]
            vector[1] = tmp
            outfile.write(s.pack(*vector))
**But when I used the converted file to run the framework, it showed me  segmentation fault like below**
![b4d30da84f440cb2291f295f54a7746](https://user-images.githubusercontent.com/47123798/64983281-c3477180-d885-11e9-848b-d91509098814.png)
Do you know what might be causing this problem? And is there a standard for your required binary edge list file? When I try to input some other binary edge list file it shows me unable to read property file. 
![f4cb3c0d590059f548e1f6612c367a6](https://user-images.githubusercontent.com/47123798/64983515-45d03100-d886-11e9-8e10-9ff98f4a6e0a.png)
Thank you very much!

**Comment by bindsch** [comment]
I did not run your conversion script, but are you sure it is correct? X-Stream sees 8298 vertices whereas the input file seems to only contain 7115. The second thing you might want to check is the type in the .ini file. Since you are adding a weight, it should be type 1, not type 2.

Regarding your second problem, the error `Unable to read property file` means there is no .ini file with the input name you provided (i.e., `scale` in this case).

**Comment by xiaogouaiyaotou** [comment]
Thank you very much. I think I found the reason.
