### ISSUE TITLE
MCST application do not seem to be running correctly?

### ISSUE THREAD

**Issue by azywait** [epfl-labos/x-stream#4]
Hi,
   I use x-stream to run MCST algorithm. I only use a tiny benchmark as follows:
![image](https://cloud.githubusercontent.com/assets/4987859/16804061/6e25f964-493c-11e6-97d8-10b636e4f906.png)
   And transfer it to binary as x-stream default input format.
   The command line to run it is:
![image](https://cloud.githubusercontent.com/assets/4987859/16804124/cc080252-493c-11e6-9681-8291f10f40eb.png)
    But, the program has entered a dead cycle. (Other algorithms run well)
![image](https://cloud.githubusercontent.com/assets/4987859/16804174/1a6dfa32-493d-11e6-94d9-7f67e6514545.png)
    Why is there such a situation? Thank you!!

**Comment by azywait** [comment]
Furthermore,
the edge format as follows:
![image](https://cloud.githubusercontent.com/assets/4987859/16804377/1b669556-493e-11e6-8eb9-6d588ff75831.png)

**Comment by bindsch** [comment]
Are you sure the graph is properly converted to binary? Is the weight converted to a float (above it seems to be an integer)?

**Comment by azywait** [comment]
I am sure that the edge weight had been converted to float.
Other applications are running well, but, only MCST run error!

**Comment by bindsch** [comment]
Alright, can you post the input file along with the corresponding ini file?

**Comment by azywait** [comment]
input file(txt format), filename: test-new-weight.data
0 1 1.000000
1 2 2.000000
2 3 3.000000
3 4 4.000000
4 5 5.000000

ini file:
![image](https://cloud.githubusercontent.com/assets/4987859/16809907/84f6f4dc-4954-11e6-935d-71a4b1cd3d9c.png)

**Comment by azywait** [comment]
Wow, maybe I know the problem.
For the MCST algorithm which x-stream implement, each edge must be two-way?
Because my graph is directed, so, it can not correctly calculate the connected component.
Isn't it?

**Comment by azywait** [comment]
Thanks for your help.

**Comment by bindsch** [comment]
Yes, MCST is an undirected algorithm. Both forward and reverse edges must be present in the input or else the algorithm will not terminate.
