### ISSUE TITLE
core/../utils/boost_log_wrapper.h:64: error: ‘BOOST_ASSERT_MSG’ was not declared in this scope

### ISSUE THREAD

**Issue by lifahao** [epfl-labos/x-stream#6]
When i try to make install,there is a error.I have installed lapack and follow the install.md :

g++ -O3 -g -Wall -Wno-unused-function -Wfatal-errors -DCOMPACT_GRAPH -DZLIB_COMPRESSION_LEVEL=Z_BEST_SPEED -msse4.2 -include core/types.h -I/usr/local/include/boost-numeric-bindings -IADOOP_HOME/include -c -o object_files/core.o core/core.cpp
In file included from core/../utils/memory_utils.h:34,
                 from core/autotuner.hpp:22,
                 from core/split_stream.hpp:21,
                 from core/disk_io.hpp:21,
                 from core/x-lib.hpp:21,
                 from core/core.cpp:19:
core/../utils/../core/hdfs_io.h:12:23: error: hdfs/hdfs.h: No such file or directory
In file included from core/autotuner.hpp:21,
                 from core/split_stream.hpp:21,
                 from core/disk_io.hpp:21,
                 from core/x-lib.hpp:21,
                 from core/core.cpp:19:
core/../utils/boost_log_wrapper.h: In destructor ‘BOOST_LOG_TRIVIAL::~BOOST_LOG_TRIVIAL()’:
core/../utils/boost_log_wrapper.h:64: error: ‘BOOST_ASSERT_MSG’ was not declared in this scope
compilation terminated due to -Wfatal-errors.
make: *** [object_files/core.o] Error 1

**Comment by bindsch** [comment]
Looks like you are missing boost.

**Comment by lifahao** [comment]
but when i yum install boost:
Package boost-1.41.0-28.el6.x86_64 already installed and latest version

**Comment by bindsch** [comment]
You need >= 1.48.
