### ISSUE TITLE
Error during build due to hdfs.h

### ISSUE THREAD

**Issue by xkitsios** [epfl-labos/x-stream#7]
Hello,

I'm trying to build x-stream. I followed your instruction at INSTALL.md.
It looks like I'm missing a library. I've installed Hadoop (http://hadoop.apache.org/) and set HADOOP_HOME.
Do you have any advise how I can fix my problem?

Thanks in advance

> $make
> g++ -O3 -g -Wall -Wno-unused-function -Wfatal-errors -DCOMPACT_GRAPH -DZLIB_COMPRESSION_LEVEL=Z_BEST_SPEED -msse4.2 -include core/types.h -I/usr/local/include/boost-numeric-bindings -IADOOP_HOME/include -c -o object_files/core.o core/core.cpp
> In file included from core/../utils/memory_utils.h:34:
> from` core/autotuner.hpp:22,
> from core/split_stream.hpp:21,
> from core/disk_io.hpp:21,
> from core/x-lib.hpp:21,
> from core/core.cpp:19:
> core/../utils/../core/hdfs_io.h:12:23: fatal error: hdfs/hdfs.h: No such file or directory
> #include <hdfs/hdfs.h>
> ^
> compilation terminated.
> make: *** [object_files/core.o] Error 1

**Comment by bindsch** [comment]
Looks like it does not find hdfs.h. Nothing a little googling can't fix ;-)

If you do not need HDFS support, might I suggest you try the `sosp` branch. We added HDFS support afterwards.

**Comment by xkitsios** [comment]
Neither `sosp` nor `master `branch don't work for me. It fails with the same compilation error.

I think In line [24](https://github.com/epfl-labos/x-stream/blob/master/Makefile#L24) from the Makefile
`EXTRA_INCLUDES+=-I$HADOOP_HOME/include`
should be
`EXTRA_INCLUDES+=-I $(HADOOP_HOME)/include`
because the result during build is
`-IADOOP_HOME/include`
and with my suggestion will be:
`-I /usr/local/hadoop/include`

Although that doesn't fix my problem.
If I find any solution, I'll update the thread.

**Comment by bindsch** [comment]
The `sosp` branch does not have hdfs support, so it should not fail on a missing hdfs.h.

**Comment by Masterchao12138** [comment]
How did you solve this problem,I have the same problem

**Comment by bindsch** [comment]
Switch to the `sosp` branch

**Comment by Masterchao12138** [comment]
Hello, I have not found the way to switch to sosp branch, can you give me some hints

**Comment by Masterchao12138** [comment]
Thank you very much for your advice. I have already run it
