### ISSUE TITLE
whether hdfs must have hadoop support?

### ISSUE THREAD

**Issue by jqcc** [epfl-labos/x-stream#9]
When I build the environment， I encountered such a problem。

`g++ -O3 -g -Wall -Wno-unused-function -Wfatal-errors -DCOMPACT_GRAPH -DZLIB_COMPRESSION_LEVEL=Z_BEST_SPEED -msse4.2 -include core/types.h -I/usr/local/include/boost-numeric-bindings -IADOOP_HOME/include -c -o object_files/core.o core/core.cpp
In file included from core/../utils/memory_utils.h:34:0,
                 from core/autotuner.hpp:22,
                 from core/split_stream.hpp:21,
                 from core/disk_io.hpp:21,
                 from core/x-lib.hpp:21,
                 from core/core.cpp:19:
core/../utils/../core/hdfs_io.h:12:23: fatal error: hdfs/hdfs.h: No such file or directory
 #include <hdfs/hdfs.h>
                       ^
compilation terminated.
make: *** [object_files/core.o] Error 1`

Do I need to have hadoop installed to get hdfs support？

**Comment by bindsch** [comment]
You need HDFS, but not necessarily Hadoop.
